/** This file is automatically generated by grunt, please DO NOT modify it directly **/
game.assets = [
    {
        "name": "S01_NewBarkTown",
        "type": "audio",
        "src": "assets/bgm/"
    },
    {
        "name": "collide",
        "type": "audio",
        "src": "assets/sfx/"
    },
    {
        "name": "door_enter",
        "type": "audio",
        "src": "assets/sfx/"
    },
    {
        "name": "door_exit",
        "type": "audio",
        "src": "assets/sfx/"
    },
    {
        "name": "escape",
        "type": "audio",
        "src": "assets/sfx/"
    },
    {
        "name": "heal",
        "type": "audio",
        "src": "assets/sfx/"
    },
    {
        "name": "jump",
        "type": "audio",
        "src": "assets/sfx/"
    },
    {
        "name": "select",
        "type": "audio",
        "src": "assets/sfx/"
    },
    {
        "name": "overworld_tiles",
        "type": "image",
        "src": "assets/img/map/overworld_tiles.png"
    },
    {
        "name": "trainer_sprite_ethan",
        "type": "image",
        "src": "assets/img/sprite/trainer_sprite_ethan.png"
    },
    {
        "name": "trainer_sprite",
        "type": "image",
        "src": "assets/img/sprite/trainer_sprite.png"
    },
    {
        "name": "S01_NewBarkTown",
        "type": "tmx",
        "src": "assets/map/S01_NewBarkTown.tmx"
    },
    {
        "name": "overworld",
        "type": "tsx",
        "src": "assets/map/overworld.tsx"
    }
];